#!/usr/bin/perl -w

use SPSE;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "SPSE",
   ReceiveHandler => \&Receive);
$UNIVERSAL::spse = SPSE->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::spse->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::spse->Execute();
